a=set(map(int,input("Enter integer for set A (coma separeted):").split(',')))
b=set(map(int,input("Enter integer for set B (coma separeted):").split(',')))
print("A:",a)
print("B:",b)
print("union:",a.union(b))
