l= float(input("enter the value of length:"))
b= float(input("enter the value of breadth:"))
area= l * b
perimeter=2 *(l+b)
print("the area of a rectangle is %.2f",area)
print("the perimeter of a rectangle is %.2f",perimeter)
radius= float(input("enter the value of radius:"))
area_2= 3.14 * (radius**2)
print("the area of a circle is %.2f:",area_2)
print("the perimeter of a circle is %.2f:", perimeter)
rad= float(input("enter the value of radius:"))
volume=((4/3) * 3.14 * (rad * rad * rad))
print(f" the volume of sphere is (volum:.2f)")
radi= float(input("enter the value of radius:"))
h=int(input("enter the height of a cylinder:"))
vol=(3.14 * (radi * radi) * h)
print("the volume of a cylinder is %.2f:",vol)
